describe('signing up', () => {
  it('allows new user to register', () => {
    cy.visit('http://localhost:3000')
    cy.get('#new_user').click()
    cy.url().should('eq', 'http://localhost:3000/#/sign-up')
    cy.get('form#new_user_form').should('exist')
    cy.get('input[name="username"]').type('Argy-Bargy').should('have.value', 'Argy-Bargy')
    cy.get('input[name="email"]').type('argybargy@test.com').should('have.value', 'argybargy@test.com')
    cy.get('input[name="location"]').type('SW1 1AA').should('have.value', 'SW1 1AA')
    cy.get('input[name="password"]').type('testpassword').should('have.value', 'testpassword')
    cy.get('input[name="passwordCheck"]').type('testpassword').should('have.value', 'testpassword')
    cy.get('form#new_user_form').submit()
    cy.url().should('eq', 'http://localhost:3000/#/')
  })
})
